# new rms deployment with image v5, external secrets via secret manager for postgres
# and Ingress with ALB.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-staging-app9
  namespace: rms-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rms-staging-app9
  template:
    metadata:
      labels:
        app: rms-staging-app9
    spec:
      containers:
      - name: rms-staging-app4
        image: 351545483064.dkr.ecr.ap-southeast-1.amazonaws.com/rms-dev:v11
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          value: "prod-rw.rms-demo.svc.cluster.local"

          #valueFrom:
            #secretKeyRef:
              #name: remote-kube-secret
              #key: host

        - name: DB_PORT
          value: "5432"

          #valueFrom:
            #secretKeyRef:
              #name: remote-kube-secret
              #key: port
              
        - name: DB_USER
          value: "stagingrms"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: username

        - name: DB_PASSWORD
          value: "stagingrms"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: password

        - name: DB_NAME
          value: "stagingrmsdb"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: dbname
      
      # Create pulsar client container that talks to Pulsar broker

      - name: rms-pulsar-staging-app4
        image: 351545483064.dkr.ecr.ap-southeast-1.amazonaws.com/rms-pulsar:v12.1
        env:
        - name: DB_HOST
          value: "prod-rw.rms-demo.svc.cluster.local"

          #valueFrom:
            #secretKeyRef:
              #name: remote-kube-secret
              #key: host

        - name: DB_PORT
          value: "5432"

          #valueFrom:
            #secretKeyRef:
              #name: remote-kube-secret
              #key: port
              
        - name: DB_USER
          value: "stagingrms"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: username

        - name: DB_PASSWORD
          value: "stagingrms"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: password

        - name: DB_NAME
          value: "stagingrmsdb"

          # valueFrom:
          #   secretKeyRef:
          #     name: remote-kube-secret
          #     key: dbname

        - name: PULSAR_URL
          value: "pulsar://k8s-pulsar-pulsarpr-9d54b5a30c-fa7bb04d53a3b8ec.elb.ap-southeast-1.amazonaws.com:6650"

        - name: REDIS_URL
          value: "redis-st-staging-ro.kvj8wl.ng.0001.apse1.cache.amazonaws.com:6379"
