apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: values.yaml
    target:
      group: apps
      kind: Deployment
      name: rms-staging-app9
      version: v1
